packaging_format = 2

id = "hat"
name = "Hat.sh"
description.en = "Encrypt and Decrypt files securely in your browser"
description.fr = "Chiffrer et déchiffrer les fichiers en toute sécurité dans votre navigateur"

version = "v2.3.6~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "hat.sh"
demo = "https://hat.sh"
admindoc = "https://hat.sh/about/"
code = "https://github.com/sh-dv/hat.sh"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "900M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/sh-dv/hat.sh/archive/refs/tags/v2.3.6.tar.gz"
        sha256 = "61012b0cb8127b5ff073e2aa489e88d750c0c1ed81f1e7115f1db03db974f64f"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]
    main.default = 3991

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
